env_1:
  env_name: CartPole-v0
  random_seed: 0
  observation_shape: !!python/tuple [4, ]
  action_shape: !!python/tuple [1, ]
  output_shape: !!python/tuple [2, ]

#env_2:
#  env_name: CartPole-v0
#  random_seed: 1
#  observation_shape: !!python/tuple [ 4, ]
#  action_shape: !!python/tuple [ 1, ]
#  output_shape: !!python/tuple [ 2, ]
#
#env_3:
#  env_name: CartPole-v0
#  random_seed: 2
#  observation_shape: !!python/tuple [ 4, ]
#  action_shape: !!python/tuple [ 1, ]
#  output_shape: !!python/tuple [ 2, ]
#
#env_4:
#  env_name: CartPole-v0
#  random_seed: 3
#  observation_shape: !!python/tuple [ 4, ]
#  action_shape: !!python/tuple [ 1, ]
#  output_shape: !!python/tuple [ 2, ]
#
#env_5:
#  env_name: CartPole-v0
#  random_seed: 4
#  observation_shape: !!python/tuple [ 4, ]
#  action_shape: !!python/tuple [ 1, ]
#  output_shape: !!python/tuple [ 2, ]
#
#env_6:
#  env_name: CartPole-v0
#  random_seed: 5
#  observation_shape: !!python/tuple [ 4, ]
#  action_shape: !!python/tuple [ 1, ]
#  output_shape: !!python/tuple [ 2, ]
#
#env_7:
#  env_name: CartPole-v0
#  random_seed: 6
#  observation_shape: !!python/tuple [ 4, ]
#  action_shape: !!python/tuple [ 1, ]
#  output_shape: !!python/tuple [ 2, ]
#
#env_8:
#  env_name: CartPole-v0
#  random_seed: 7
#  observation_shape: !!python/tuple [ 4, ]
#  action_shape: !!python/tuple [ 1, ]
#  output_shape: !!python/tuple [ 2, ]