env_1:
  env_name: LunarLander-v2
  random_seed: 0
  observation_shape: !!python/tuple [8, ]
  action_shape: !!python/tuple [1, ]
  output_shape: !!python/tuple [4, ]

#env_2:
#  env_name: LunarLander-v2
#  random_seed: 1
#  observation_shape: !!python/tuple [8, ]
#  action_shape: !!python/tuple [1, ]
#  output_shape: !!python/tuple [4, ]
#
#env_3:
#  env_name: LunarLander-v2
#  random_seed: 2
#  observation_shape: !!python/tuple [8, ]
#  action_shape: !!python/tuple [1, ]
#  output_shape: !!python/tuple [4, ]
#
#env_4:
#  env_name: LunarLander-v2
#  random_seed: 3
#  observation_shape: !!python/tuple [8, ]
#  action_shape: !!python/tuple [1, ]
#  output_shape: !!python/tuple [4, ]