lr_critic: 1.e-3
lr_actor: 1e-4
std: 0.5
optimizer: Adam
buffer_type: uniform
buffer_size: 50000
gamma: 0.995
update_epoch: 10
update_interval: 100
network_name_critic: vanilla_mlp_critic
network_name_actor: vanilla_mlp_actor
observation_shape: null
action_shape: null
output_shape: null
batch_size: 512
std_decay_rate: 5.e-7
tau: 1.e-5